# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

build_program:
  image: gcc
  stage: build
  script:
    - cd code
    - make
  artifacts:
    paths:
      - code/sudoku.o
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    paths:
      - "code/*.o"

build_pdf:
  image: tianon/latex
  stage: build
  script:
    - cd report
    - rm -f project_report.pdf
    - latexmk -pdf project_report.tex
    - latexmk -pdf project_report.tex #Build twice for references
  artifacts:
    paths:
      - report/project_report.pdf

# run tests using the binary built before
# Use basic ubuntu core to run and save to output.txt
test_program:
  image: gcc
  stage: test
  script:
    - cd code
    - make test