# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

stages:
  - build
  - test
  - coverage

build_program:
  image: gcc
  stage: build
  script:
    - cd code
    - make
  artifacts:
    untracked: true
    paths:
      - code/*
      
build_pdf:
  image: tianon/latex
  stage: build
  script:
    - cd report
    - rm -f project_report.pdf
    - latexmk -pdf project_report.tex
  artifacts:
    paths:
      - report/project_report.pdf
  when: manual

# run tests using the binary built before
# Use basic ubuntu core to run and save to test_output.txt
test_program:
  image: gcc
  stage: test
  script:
    - cd code
    - make test
  artifacts:
    untracked: true
    paths:
      - code/*
      
test_coverage:
  image: gcc
  stage: coverage
  script:
    - echo Acquire::http::Proxy http://"$HTTP_PROXY"'/;' > /etc/apt/apt.conf
    - echo Acquire::https::Proxy http://"$HTTP_PROXY"'/;' >> /etc/apt/apt.conf
    - echo Acquire::ftp::Proxy http://"$HTTP_PROXY"'/;' >> /etc/apt/apt.conf
    - cat /etc/apt/apt.conf
    - apt-get update
    - apt-get install python-pip -y
    - pip install gcovr
    - cd code
    - make coverage
  artifacts:
    untracked: true
    paths:
      - code/*
